import { symbols } from '../../symbols';
import { syntaxAnalysis } from '../syntaxAnalysis';

describe('syntaxAnalysis', () => {
    it('should identify while loops', () => {
        const tokens = [
            symbols.program,
            symbols.identificador,
            symbols[';'],
            symbols.const,
            symbols.identificador,
            symbols['='],
            symbols.inteiro,
            symbols[';'],
            symbols.var,
            symbols.identificador,
            symbols[':'],
            symbols.array,
            symbols['['],
            symbols.inteiro,
            symbols['..'],
            symbols.inteiro,
            symbols[']'],
            symbols.of,
            symbols.integer,
            symbols[';'],
            symbols.begin,
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols[':='],
            symbols.inteiro,
            symbols[';'],
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols[':='],
            symbols.inteiro,
            symbols[';'],
            symbols.while,
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols['<='],
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols.do,
            symbols.begin,
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols[':='],
            symbols.identificador,
            symbols['['],
            symbols.inteiro,
            symbols[']'],
            symbols['-'],
            symbols.identificador,
            symbols[';'],
            symbols.end,
            symbols[';'],
            symbols.end,
            symbols['.']
        ].reverse();
        expect(() => syntaxAnalysis(tokens)).not.toThrow();
        expect(tokens).toEqual([]);
    });
});
