import { symbols } from '../../symbols';
import { syntaxAnalysis } from '../syntaxAnalysis';

describe('syntaxAnalysis', () => {
    it('should handle label and goto', () => {
        const tokens = [
            { line: 1, id: symbols.program },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.var },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[','] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[','] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[','] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':'] },
            { line: 1, id: symbols.integer },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.begin },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':='] },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':='] },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.while },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols['='] },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols.do },
            { line: 1, id: symbols.begin },
            { line: 1, id: symbols.readln },
            { line: 1, id: symbols['('] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[')'] },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.if },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols['<'] },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols.then },
            { line: 1, id: symbols.goto },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':='] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols['+'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':='] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols['+'] },
            { line: 1, id: symbols.inteiro },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.end },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[':='] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols['/'] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.writeln },
            { line: 1, id: symbols['('] },
            { line: 1, id: symbols.literal },
            { line: 1, id: symbols[','] },
            { line: 1, id: symbols.identificador },
            { line: 1, id: symbols[')'] },
            { line: 1, id: symbols[';'] },
            { line: 1, id: symbols.end },
            { line: 1, id: symbols['.'] }
        ].reverse();
        expect(() => syntaxAnalysis(tokens)).not.toThrow();
        expect(tokens).toEqual([]);
    });
});
