export const nonTerminalSymbols = {
    programa: 52,
    bloco: 53,
    declaracaoRot: 54,
    lId: 55,
    repident: 56,
    declaracaoConst: 57,
    ldConst: 58,
    declaracaoVar: 59,
    ldVar: 60,
    tipo: 61,
    declaracaoProc: 62,
    defpar: 63,
    corpo: 64,
    repComando: 65,
    comando: 66,
    rcomid: 67,
    rVar: 68,
    parametros: 69,
    repeticaoParametro: 70,
    elseparte: 71,
    variavel: 72,
    variavel1: 73,
    repeticaoVariavel: 74,
    itemSaida: 75,
    repeticaoItem: 76,
    expressao: 77,
    repeticaoExpressaoImp: 78,
    expressaoImp: 79,
    repeticaoExpressao: 80,
    termo: 81,
    repeticaoTermo: 82,
    fator: 83,
    condicaoCase: 84,
    contCase: 85,
    repeticaoInteiro: 86,
    semefeito: 87
} as const;

export const nonTerminalSymbolsIds = {
    52: 'programa',
    53: 'bloco',
    54: 'declaracaoRot',
    55: 'lId',
    56: 'repident',
    57: 'declaracaoConst',
    58: 'ldConst',
    59: 'declaracaoVar',
    60: 'ldVar',
    61: 'tipo',
    62: 'declaracaoProc',
    63: 'defpar',
    64: 'corpo',
    65: 'repComando',
    66: 'comando',
    67: 'rcomid',
    68: 'rVar',
    69: 'parametros',
    70: 'repeticaoParametro',
    71: 'elseparte',
    72: 'variavel',
    73: 'variavel1',
    74: 'repeticaoVariavel',
    75: 'itemSaida',
    76: 'repeticaoItem',
    77: 'expressao',
    78: 'repeticaoExpressaoImp',
    79: 'expressaoImp',
    80: 'repeticaoExpressao',
    81: 'termo',
    82: 'repeticaoTermo',
    83: 'fator',
    84: 'condicaoCase',
    85: 'contCase',
    86: 'repeticaoInteiro',
    87: 'semefeito'
} as const;

export type nonTerminalKeys = keyof typeof nonTerminalSymbols;
export type nonTerminalSymbolsIdsType =
    typeof nonTerminalSymbols[keyof typeof nonTerminalSymbols];

export const nonTerminalSymbolsValues = Object.values(nonTerminalSymbols);
