export const symbols = [
    { id: 1, symbol: 'program' },
    { id: 2, symbol: 'label' },
    { id: 3, symbol: 'const' },
    { id: 4, symbol: 'var' },
    { id: 5, symbol: 'procedure' },
    { id: 6, symbol: 'begin' },
    { id: 7, symbol: 'end' },
    { id: 8, symbol: 'integer' },
    { id: 9, symbol: 'array' },
    { id: 10, symbol: 'of' },
    { id: 11, symbol: 'call' },
    { id: 12, symbol: 'goto' },
    { id: 13, symbol: 'if' },
    { id: 14, symbol: 'then' },
    { id: 15, symbol: 'else' },
    { id: 16, symbol: 'while' },
    { id: 17, symbol: 'do' },
    { id: 18, symbol: 'repeat' },
    { id: 19, symbol: 'until' },
    { id: 20, symbol: 'readln' },
    { id: 21, symbol: 'writeln' },
    { id: 22, symbol: 'or' },
    { id: 23, symbol: 'and' },
    { id: 24, symbol: 'not' },
    // { id: 25, symbol: 'identificador' },
    // { id: 26, symbol: 'inteiro' },
    { id: 27, symbol: 'for' },
    { id: 28, symbol: 'to' },
    { id: 29, symbol: 'case' },
    { id: 30, symbol: '+' },
    { id: 31, symbol: '-' },
    { id: 32, symbol: '*' },
    { id: 33, symbol: '/' },
    { id: 34, symbol: '[' },
    { id: 35, symbol: ']' },
    { id: 36, symbol: '(' },
    { id: 37, symbol: ')' },
    { id: 38, symbol: ':=' },
    { id: 39, symbol: ':' },
    { id: 40, symbol: '=' },
    { id: 41, symbol: '>' },
    { id: 42, symbol: '>=' },
    { id: 43, symbol: '<' },
    { id: 44, symbol: '<=' },
    { id: 45, symbol: '<>' },
    { id: 46, symbol: ',' },
    { id: 47, symbol: ';' },
    //  { id: 48, symbol: 'literal' },
    { id: 49, symbol: '.' },
    { id: 50, symbol: '..' },
    { id: 51, symbol: '$' }
];
